Issue 12
turingschool-projects/1610-remember-1 pull request #17
Opened 2017-02-14 22:58 UTC by bekahlundy

## Purpose
User can revert an unsaved reminder to its previous state mid-edit.

When actively editing a reminder, if the reminder has unsaved changes, the user will see a button to rollback unsaved changes.
When clicked it will automatically rollback the attributes of the reminder to its original, clean state.
Pro tip: If you’re doing something that seems hard, maybe you should check the Ember Data API docs for a hint...

[Issue #12](https://github.com/turingschool-projects/1610-remember-1/issues/12)

## Approach

We just created a 'revert' button that called an action called 'revertReminder.' We then added that function to the edit component and used model.rollback().

### Learning

Just referenced Ember docs

[Ember Rollback Docs](http://emberjs.com/api/data/classes/DS.Model.html#method_rollbackAttributes)

### Open Questions and Pre-Merge TODOs

- [x] Add revert button and action to roll back attributes
- [x] Fix broken acceptance tests
- [x] Add new acceptance tests

### Test coverage 

We wrote a test that visits the page, enters data, hits submit, clicks on entry, clicks edit button, fills in changed text, hits the 'revert' button, and checks to see that the text did not change.

### Follow-up tasks

- [Issue #13](https://github.com/turingschool-projects/1610-remember-1/issues/13)

### Screenshots

#### Before
<img width="600" alt="screen shot 2017-02-14 at 3 44 52 pm" src="https://cloud.githubusercontent.com/assets/20376939/22953018/8f1fe550-f2cc-11e6-96c3-b6dbc2784620.png">

#### After
<img width="469" alt="screen shot 2017-02-14 at 3 21 21 pm" src="https://cloud.githubusercontent.com/assets/20376939/22952285/9810f936-f2c9-11e6-8943-d9e351c0c101.png">
<img width="541" alt="screen shot 2017-02-14 at 3 21 38 pm" src="https://cloud.githubusercontent.com/assets/20376939/22952305/afd63504-f2c9-11e6-8cf2-56f6a78ca0ae.png">
<img width="469" alt="screen shot 2017-02-14 at 3 21 21 pm" src="https://cloud.githubusercontent.com/assets/20376939/22952308/b1e7d91a-f2c9-11e6-8a2e-3a5c77ea06c1.png">
<img width="478" alt="screen shot 2017-02-14 at 3 18 35 pm" src="https://cloud.githubusercontent.com/assets/20376939/22952312/b4efc0c8-f2c9-11e6-92fb-0d7fcee03291.png">
<img width="572" alt="screen shot 2017-02-14 at 3 17 51 pm" src="https://cloud.githubusercontent.com/assets/20376939/22952320/baf7a38c-f2c9-11e6-8a45-b83f35c38d1d.png">

close #11 
close #12

2017-02-14 23:03 UTC, martensonbj requested changes

2017-02-14 23:03 UTC, martensonbj commented on app/templates/components/edit-reminder.hbs
> +    {{action 'revertReminder' model on="click"}}>
Let's add a conditional here that only displays this button (or only makes it active - your choice) if there are dirty attributes on the model. [docs](https://guides.emberjs.com/v2.11.0/models/creating-updating-and-deleting-records/#toc_persisting-records)

2017-02-14 23:34 UTC, bekahlundy commented
@martensonbj We added the if statement!

2017-02-15 00:02 UTC, Tman22 commented
Nice job.

2017-02-15 00:02 UTC, merged