Add Reminders from
turingschool-projects/1610-remember-1 pull request #4
Opened 2017-02-08 22:18 UTC by bekahlundy

## Purpose

- When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.

- Each reminder should have a class of .spec-reminder-item.

- There is a failing test set up in tests/acceptance/reminder-list-test.js.

[Issue #1](https://github.com/turingschool-projects/1610-remember-1/issues/1)

## Approach

We had to build an app with our boilerplate. We created appropriate routes, templates, and model and connected them. 

### Learning

We primarily referenced the ember docs. 

[Getting started with Ember](https://guides.emberjs.com/v2.11.0/getting-started/quick-start/)
[Ember tuturial](https://guides.emberjs.com/v2.11.0/tutorial/ember-cli/)

### Open Questions and Pre-Merge TODOs

- [x] Set up routes and model for our application
- [x] Change Ember version to 2.11.0
- [x] Reminders render on page
- [x] Add class .spec-reminder-item to li tags
- [x] Route on page load is /
- [x] Tests run and fail

### Test coverage 

There were two tests written for us. There is a test to check if there are 5 reminders rendering on the homepage, and a test to check when something is clicked.

### Merge Dependencies and Related Work

N/A ???

### Follow-up tasks

- [Issue #2](https://github.com/turingschool-projects/1610-remember-1/issues/2)

### Screenshots

#### Before
<img width="886" alt="screen shot 2017-02-08 at 3 13 14 pm" src="https://cloud.githubusercontent.com/assets/20376939/22759835/2c49ef08-ee11-11e6-9266-f6f3163ee615.png">
#### After
<img width="699" alt="screen shot 2017-02-08 at 3 14 46 pm" src="https://cloud.githubusercontent.com/assets/20376939/22759893/5ed5c6c2-ee11-11e6-82a4-6db311521d85.png">
<img width="1035" alt="screen shot 2017-02-08 at 3 17 07 pm" src="https://cloud.githubusercontent.com/assets/20376939/22759970/b3404264-ee11-11e6-87f5-c90d4fc23805.png">

2017-02-08 22:56 UTC, martensonbj requested changes
Few things! Good work 👍

2017-02-08 22:56 UTC, martensonbj commented on app/routes/reminders.js
> +    return ['bekah needs to get more banana chips', 'josh needs to do a cartwheel', 'Bekah needs to get out of her funk', 'We both need to listen to some funky music', 'make money']
1) Let's get bekah out of her funk AND more cartwheels would be good. 2. Let's use Mirage to grab these models, we don't need to hardcode them. Check out [docs for how to findAll records from a store](https://guides.emberjs.com/v2.11.0/models/finding-records/#toc_retrieving-multiple-records) -- this call will trigger Mirage to hand you whatever it's created instead.

2017-02-08 22:56 UTC, martensonbj commented on app/templates/application.hbs
> +<h1>hello</h1>
I'm assuming you meant to delete this h1 - unless that's an intentional title in which case let's capitalize it.

2017-02-08 22:56 UTC, martensonbj commented on app/templates/components/reminders-list.hbs
> +  <li class='spec-reminder-item'>{{reminder}}</li>
indent please :)

2017-02-08 22:56 UTC, martensonbj commented on app/templates/index.hbs
> +{{outlet}}
We don't need this file at all - can be deleted

2017-02-08 22:56 UTC, martensonbj commented on tests/integration/components/reminders-list-test.js
> +import { moduleForComponent, test } from 'ember-qunit';
This is all boilerplate code - lets add some sort of assertion that indicates you know what this file does. In this case I would at least test that there is an h1, and 5 elements with the class of '.spec-reminder-item'.

2017-02-08 22:56 UTC, martensonbj commented on tests/unit/routes/index-test.js
> +import { moduleFor, test } from 'ember-qunit';
We won't need any route tests. Routes are generally tested in acceptance tests when you run the line `visit('/')` and then assert that the current URL is what you expect. We can delete this file.

2017-02-08 22:56 UTC, martensonbj commented on tests/unit/routes/reminders-test.js
> +import { moduleFor, test } from 'ember-qunit';
See above comment on route tests.

2017-02-08 22:56 UTC, martensonbj commented on app/templates/application.hbs
> +<h1>hello</h1>
Also we can remove comments.

2017-02-09 20:35 UTC, martensonbj commented
Status on these changes? Checking in to make sure youv'e seen them. Make sure any changes related to this PR are pushed up to the same branch this PR lives on.

2017-02-09 22:01 UTC, bekahlundy commented
@martensonbj Here are our changes! ✨

2017-02-09 23:06 UTC, bekahlundy commented
Hey @Tman22 @martensonbj , we made the changes that Taylor had talked to us about. Deleted some files and extra code and only included issue 1 in this pr.

2017-02-10 00:18 UTC, rrgayhart commented on tests/acceptance/reminder-list-test.js
> +    assert.equal(currentURL(), '/', 'curren turl is root');
@bekahlundy - This is misspelled

2017-02-10 00:21 UTC, martensonbj approved these changes

2017-02-10 00:21 UTC, merged

2017-02-10 00:21 UTC, martensonbj commented on tests/acceptance/reminder-list-test.js
> +    assert.equal(currentURL(), '/', 'curren turl is root');
@rrgayhart that was actually my fault - they're fixing it in the next PR